# version: "3.8"
services:
  bugtrackerfrontend:
    build:
      context: ./frontend
      # dockerfile: Dockerfile
    image: bug-tracker-ik_bugtrackerfrontend
    ports:
      - "3000:3000"

  bugtrackerbackend:
    build:
      context: ./backend
      # dockerfile: Dockerfile
    image: bug-tracker-ik_bugtrackerbackend
    ports:
      - "4000:4000"
